defaults: &defaults 
  adapter: postgresql 
  encoding: unicode 
  pool: 5
  username: thinkblue 
  password: thinkblue
  host: 127.0.0.1

development:
  database: wedding_development 
  <<: *defaults

test: &test
  database: wedding_test 
  <<: *defaults

production:
  database: wedding_production 
  <<: *defaults
cucumber:
  <<: *test